language: node_js
node_js:
  - 0.8
before_script:
  - npm install -g bower
  - bower install
  - make
  - node server.js &
  - sleep 5
script: phantomjs bower_components/qunit/addons/phantomjs/runner.js 'http://localhost:3000/test/index.html'
