language: node_js
node_js:
  - 0.6
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - sudo node server.js &
  - sleep 5
script: phantomjs test/lib/qunit/run-qunit.js "http://localhost:3000/test/"